// Mirrors web app src/data/labTests.ts — test IDs map to category names
const CATEGORIES: { name: string; tests: { id: string; name: string }[] }[] = [
  { name: 'Inflammation', tests: [{ id: 'crp', name: 'CRP' }, { id: 'procalcitonin', name: 'Procalcitonin' }] },
  { name: 'Blood Gases', tests: [{ id: 'abg', name: 'ABG' }, { id: 'vbg', name: 'VBG' }, { id: 'lactate', name: 'Lactate' }] },
  { name: 'Liver Function', tests: [{ id: 'bil-t', name: 'Bil (T)' }, { id: 'bil-d', name: 'Bil (D)' }, { id: 'ast', name: 'AST' }, { id: 'alt', name: 'ALT' }, { id: 'alb', name: 'ALB' }, { id: 'tp', name: 'TP' }, { id: 'ggt', name: 'GGT' }, { id: 'alk-ph', name: 'Alk Ph' }, { id: 'amylase', name: 'Amylase' }, { id: 'lipase', name: 'Lipase' }] },
  { name: 'Kidney Function', tests: [{ id: 'creatinine', name: 'Creatinine' }, { id: 'urea', name: 'Urea' }, { id: 'uric-acid', name: 'Uric acid' }, { id: 'egfr', name: 'eGFR' }, { id: 'na', name: 'Na' }, { id: 'k', name: 'K' }, { id: 'ca-total', name: 'Ca (Total)' }, { id: 'ca-ionized', name: 'Ca (Ionized)' }, { id: 'mg', name: 'Mg' }, { id: 'phosphorus', name: 'Phosphorus' }] },
  { name: 'Cardiac Profile', tests: [{ id: 'ck-mb', name: 'CK-MB' }, { id: 'ck-total', name: 'CK-Total' }, { id: 'troponin-i', name: 'Troponin I' }, { id: 'myoglobin', name: 'Myoglobin' }] },
  { name: 'Lipid Profile', tests: [{ id: 'cholesterol', name: 'Cholesterol' }, { id: 'hdl', name: 'HDL' }, { id: 'ldl', name: 'LDL' }, { id: 'triglycerides', name: 'Triglycerides' }, { id: 'vldl', name: 'VLDL' }] },
  { name: 'Diabetes Profile', tests: [{ id: 'fbs', name: 'FBS' }, { id: '2hrpp', name: '2HrPP' }, { id: 'rbs', name: 'RBS' }, { id: 'hba1c', name: 'HbA1c' }, { id: 'insulin', name: 'Insulin' }, { id: 'c-peptide', name: 'C-Peptide' }, { id: 'eag', name: 'eAG' }, { id: 'ogct', name: 'OGCT' }] },
  { name: 'Hematology', tests: [{ id: 'cbc', name: 'CBC' }, { id: 'esr', name: 'ESR' }, { id: 'abo-rh', name: 'ABO/RH' }, { id: 'fe', name: 'Fe' }, { id: 'tibc', name: 'TIBC' }, { id: 'ferritin', name: 'Ferritin' }, { id: 'ldh', name: 'LDH' }, { id: 'erythropoietin', name: 'Erythropoietin' }, { id: 'haptoglobin', name: 'Haptoglobin' }, { id: 'reticulocyte-count', name: 'Reticulocyte count' }, { id: 'coombs-direct', name: 'Coombs Direct' }, { id: 'coombs-indirect', name: 'Coombs Indirect' }, { id: 'g6pd-qualitative', name: 'G6PD Qualitative' }, { id: 'g6pd-quantitative', name: 'G6PD Quantitative' }, { id: 'pyruvate-kinase', name: 'Pyruvate Kinase' }, { id: 'hb-electrophoresis', name: 'HB electrophoresis' }] },
  { name: 'Multiple Myeloma', tests: [{ id: 'spep', name: 'SPEP' }, { id: 'immunofixation', name: 'Immunofixation' }, { id: 'quantitative-immunoglobulin', name: 'Quantitative immunoglobulin' }] },
  { name: 'Thyroid', tests: [{ id: 't3', name: 'T3' }, { id: 'free-t3', name: 'Free T3' }, { id: 't4', name: 'T4' }, { id: 'free-t4', name: 'Free T4' }, { id: 'tsh', name: 'TSH' }, { id: 'fti', name: 'FTI' }, { id: 'tbg', name: 'TBG' }, { id: 'calcitonin', name: 'Calcitonin' }, { id: 'thyroid-autoantibodies', name: 'Thyroid Autoantibodies' }, { id: 'nse', name: 'NSE' }] },
  { name: 'Parathyroid', tests: [{ id: 'pth-intact', name: 'PH (Intact)' }] },
  { name: 'Infertility', tests: [{ id: 'psh', name: 'PSH' }, { id: 'lh', name: 'LH' }, { id: 'prl', name: 'PRL' }, { id: 'e2', name: 'E2' }, { id: 'testosterone', name: 'Testosterone' }, { id: 'free-testosterone', name: 'Free Testosterone' }, { id: 'fsh', name: 'FSH' }, { id: 'progesterone', name: 'Progesterone' }, { id: 'dht-dhea-dhea-s', name: 'DHT-DHEA-DHEA-S' }] },
  { name: 'Pregnancy', tests: [{ id: 'b-hcg-qualitative', name: 'B-hCG Qualitative' }, { id: 'b-hcg-quantitative', name: 'B-hCG Quantitative' }] },
  { name: 'Hypertension', tests: [{ id: 'renin', name: 'Renin' }, { id: 'vma', name: 'VMA' }, { id: 'aldosterone', name: 'Aldosterone' }, { id: 'catecholamine', name: 'Catecholamine' }, { id: 'adrenaline', name: 'Adrenaline' }, { id: 'noradrenaline', name: 'Noradrenaline' }, { id: 'dopamine', name: 'Dopamine' }, { id: 'metanephirine', name: 'Metanephirine' }, { id: 'cortisol-am-pm', name: 'Cortisol AM / PM' }] },
  { name: 'Pituitary', tests: [{ id: 'acth', name: 'ACTH' }, { id: 'gh', name: 'GH' }] },
  { name: 'Infectious Disease', tests: [{ id: 'tb-dna-pcr', name: 'TB-DNA by PCR' }, { id: 'quantiferon-tb', name: 'QuantiFERON-TB gold plus' }, { id: 'typhoid-widal', name: 'Typhoid: Widal' }, { id: 'brucella-serology', name: 'Brucella: Serology' }, { id: 'chlamydia-antigen', name: 'Chlamydia: Antigen' }, { id: 'chlamydia-antibody', name: 'Chlamydia: Antibody' }, { id: 'syphilis-tpha', name: 'Syphilis: TPHA' }, { id: 'syphilis-vdrl', name: 'Syphilis: VDRL' }, { id: 'syphilis-rpr', name: 'Syphilis: RPR' }, { id: 'syphilis-fta', name: 'Syphilis: FTA' }, { id: 'helicobacter-saliva', name: 'Helicobacter: Saliva' }, { id: 'helicobacter-serology', name: 'Helicobacter: Serology' }, { id: 'helicobacter-igg-iga-ab', name: 'Helicobacter: IgG / IgA Ab' }] },
  { name: 'Virology', tests: [{ id: 'sars-cov2-rapid-ag', name: 'SARS-Cov-2: Rapid Test (Ag)' }, { id: 'sars-cov2-ab-igm-igg', name: 'SARS-Cov-2: Ab IgM / IgG' }, { id: 'sars-cov2-rt-pcr', name: 'SARS-Cov-2: rt-PCR' }, { id: 'h1n1-real-time', name: 'H1N1: Real time' }, { id: 'h1n1-pcr-screening', name: 'H1N1: PCR Screening A/B' }, { id: 'hpv-pcr', name: 'Human papillomavirus: HPV-PCR' }, { id: 'hsv1-igm-igg', name: 'HSV(I): IgM / IgG' }, { id: 'hsv1-pcr', name: 'HSV(I): PCR' }, { id: 'hsv2-igm-igg', name: 'HSV(II): IgM / IgG' }, { id: 'hsv2-pcr', name: 'HSV(II): PCR' }, { id: 'ebv-vca-igm', name: 'EBV: VCA-IgM' }, { id: 'ebv-vca-igg', name: 'EBV: VCA-IgG' }, { id: 'ebna-igg', name: 'EBNA-IgG' }, { id: 'hiv-ag-ab', name: 'AIDS: HIV Ag / Ab' }, { id: 'hiv-pcr', name: 'AIDS: HIV PCR' }] },
  { name: 'Hepatitis Markers', tests: [{ id: 'hav-igm', name: 'HAV: HAV-IgM' }, { id: 'hav-total', name: 'HAV: HAV total' }, { id: 'hbsag', name: 'HBV: HBsAg' }, { id: 'hbsab', name: 'HBV: HBsAb' }, { id: 'hbc-igm', name: 'HBV: HBc IgM' }, { id: 'hbc-total', name: 'HBV: HBc total' }, { id: 'hbeag', name: 'HBV: HBeAg' }, { id: 'hbeab', name: 'HBV: HBeAb' }, { id: 'hcv-igg', name: 'HCV: HCV-IgG' }, { id: 'hcv-lia', name: 'HCV: LIA' }, { id: 'hcv-rna-rt-pcr', name: 'HCV: HCV-RNA rt-PCR' }] },
  { name: 'Autoantibodies', tests: [{ id: 'c3', name: 'C3' }, { id: 'c4', name: 'C4' }, { id: 'rf', name: 'RF' }, { id: 'amyloid-a', name: 'Amyloid a' }, { id: 'ana', name: 'ANA' }, { id: 'dsdna', name: 'dsDNA' }, { id: 'asma', name: 'ASMA' }, { id: 'anti-ccp', name: 'Anti-ccp' }, { id: 'apca', name: 'APCA' }, { id: 'rana', name: 'RANA' }, { id: 'ssb-la', name: 'SSb(La)' }, { id: 'ssa-ro', name: 'SSA(Ro)' }, { id: 'scl-70', name: 'SCL-70' }, { id: 'anca', name: 'ANCA' }, { id: 'lkm-jo-1', name: 'LKM JO-1' }, { id: 'histone', name: 'Histone' }, { id: 'antisperm-ab', name: 'Antisperm Ab' }, { id: 'antigliadine-ab', name: 'AntiGliadine Ab' }, { id: 'anti-myosin-ab', name: 'Anti-Myosin Ab' }, { id: 'homa-test', name: 'Homa Test' }, { id: 'anti-insulin-ab', name: 'Anti-Insulin Ab' }, { id: 'anti-thyroid-ab', name: 'Anti-thyroid Ab' }, { id: 'anti-intrinsic-factor', name: 'Anti-Intrinsic factor' }, { id: 'hla-b27-b5', name: 'HLA(B27 - B5)' }, { id: 'autoantibody-profile', name: 'Autoantibody profile' }, { id: 'ige-total-specific', name: 'IgE total/specific (RAST)' }] },
  { name: 'Vitamins', tests: [{ id: 'vit-d-1-25-oh', name: 'Vit D (1.25 OH)' }, { id: 'vit-d3-25-oh', name: 'Vit D3 (25 OH)' }, { id: 'serum-b12', name: 'Serum B12' }, { id: 'folate', name: 'Folate' }] },
  { name: 'Hemostatic Profile', tests: [{ id: 'pt', name: 'PT' }, { id: 'aptt', name: 'aPTT' }, { id: 'fibrinogen', name: 'Fibrinogen' }, { id: 'd-dimer', name: 'D-Dimer' }, { id: 'fdps', name: "FDP's" }, { id: 'platelet-abs', name: 'Platelet Abs' }] },
  { name: 'Thrombophilia', tests: [{ id: 'protein-c', name: 'Protein C' }, { id: 'protein-s', name: 'Protein S' }, { id: 'anti-throm-iii', name: 'Anti Throm III' }, { id: 'factor-v-leiden', name: 'Factor V Leiden' }, { id: 'lupus-anticoag', name: 'Lupus Anticoag' }, { id: 'apcr', name: 'APCR' }, { id: 'anti-phospholipid-ab-igg', name: 'Anti-Phospholipid Ab IgG' }, { id: 'antib2-glycoprotein', name: 'AntiB2 Glycoprotein' }, { id: 'homocysteine', name: 'Homocysteine' }, { id: 'anti-cardiolipin', name: 'Anti Cardiolipin' }, { id: 'factor-assay', name: 'Factor Assay' }] },
  { name: 'Tumor Markers', tests: [{ id: 'psa-total', name: 'PSA (Total)' }, { id: 'psa-free', name: 'PSA (Free)' }, { id: 'pap', name: 'PAP' }, { id: 'breast-ca15-3', name: 'CA 15.3' }, { id: 'breast-cea', name: 'CEA (Breast)' }, { id: 'bladder-tpa', name: 'TPA (Bladder)' }, { id: 'bladder-cea', name: 'CEA (Bladder)' }, { id: 'bladder-ca50', name: 'CA50' }, { id: 'cervix-scc', name: 'SCC' }, { id: 'ovary-ca125', name: 'CA125' }, { id: 'ovary-ca72-4', name: 'CA72.4' }, { id: 'liver-cea', name: 'CEA (Liver)' }, { id: 'liver-afp', name: 'AFP' }, { id: 'liver-ca19-9', name: 'CA19.9' }, { id: 'liver-pivkaii', name: 'PIVKAII' }, { id: 'git-cea', name: 'CEA (GIT)' }, { id: 'git-ca19-9', name: 'CA19.9 (GIT)' }, { id: 'git-tpa', name: 'TPA (GIT)' }] },
  { name: 'Toxicology', tests: [{ id: 'lithium', name: 'Lithium' }, { id: 'digoxin', name: 'Digoxin' }, { id: 'theophylline', name: 'Theophylline' }, { id: 'methotrexate', name: 'Methotrexate' }, { id: 'cyclosporine', name: 'Cyclosporine' }, { id: 'other-drugs', name: 'Other Drugs' }] },
  { name: 'Stool Tests', tests: [{ id: 'stool', name: 'Stool' }, { id: 'occult-blood', name: 'Occult blood in stool' }, { id: 'rotavirus', name: 'Rotavirus' }, { id: 'helicobacter-ag', name: 'Helicobacter Ag' }, { id: 'reducing-sugar', name: 'Reducing Sugar' }, { id: 'calprotectin', name: 'Calprotectin' }] },
  { name: 'Urine Tests', tests: [{ id: 'urine', name: 'Urine' }, { id: 'micro-albuminuria', name: 'Micro albuminuria' }, { id: 'acr', name: 'ACR' }, { id: 'protein-creatinine-ratio', name: 'Protein/Creatinine ratio' }, { id: 'b-hcg-pregnancy', name: 'B-hCG Pregnancy' }, { id: 'bj-protein', name: 'BJ Protein' }, { id: 'drugs-of-abuse', name: 'Drugs of Abuse' }] },
  { name: 'Biological Fluids', tests: [{ id: 'csf', name: 'CSF' }, { id: 'pleural', name: 'Pleural' }, { id: 'ascitic', name: 'Ascitic' }, { id: 'synovial', name: 'Synovial' }, { id: 'adenosine-deaminase', name: 'Adenosine deaminase' }, { id: 'semen', name: 'Semen' }] },
  { name: 'Cytogenetics', tests: [{ id: 'karyotypin', name: 'Karyotypin' }, { id: 'down-syndrome', name: 'Down syndrome' }] },
];

// testId → { name, category }
export const LAB_LOOKUP: Record<string, { name: string; cat: string }> = {};
for (const cat of CATEGORIES) {
  for (const t of cat.tests) {
    LAB_LOOKUP[t.id] = { name: t.name, cat: cat.name };
  }
}

export function groupLabTests(testsObj: Record<string, boolean>): { cat: string; tests: string[] }[] {
  const groups: Record<string, string[]> = {};
  for (const [id, selected] of Object.entries(testsObj)) {
    if (!selected) continue;
    const found = LAB_LOOKUP[id];
    const catName = found?.cat ?? 'Others';
    const testName = found?.name ?? id;
    if (!groups[catName]) groups[catName] = [];
    groups[catName].push(testName);
  }
  return Object.entries(groups).map(([cat, tests]) => ({ cat, tests }));
}
