// Mirrors web app src/data/radiologyTests.ts — compact lookup
const CATEGORIES: { name: string; tests: { id: string; name: string }[] }[] = [
  { name: 'X-Ray: Chest', tests: [{ id: 'xray-chest-pa-lateral', name: 'Chest X-ray (PA & Lateral)' }, { id: 'xray-chest-ap-portable', name: 'Chest X-ray (AP / Portable)' }, { id: 'xray-chest-lateral-decubitus', name: 'Chest X-ray (Lateral Decubitus)' }, { id: 'xray-chest-lordotic', name: 'Chest X-ray (Lordotic View)' }, { id: 'xray-rib-series', name: 'Rib Series' }] },
  { name: 'X-Ray: Abdomen', tests: [{ id: 'xray-kub', name: 'Abdominal X-ray (KUB)' }, { id: 'xray-acute-abdominal-series', name: 'Acute Abdominal Series' }] },
  { name: 'X-Ray: Spine', tests: [{ id: 'xray-cervical-spine', name: 'Cervical Spine X-ray' }, { id: 'xray-thoracic-spine', name: 'Thoracic Spine X-ray' }, { id: 'xray-lumbar-spine', name: 'Lumbar Spine X-ray' }, { id: 'xray-lumbosacral', name: 'Lumbosacral Spine X-ray' }, { id: 'xray-sacrum-coccyx', name: 'Sacrum / Coccyx X-ray' }, { id: 'xray-scoliosis-series', name: 'Scoliosis Series' }, { id: 'xray-flexion-extension', name: 'Flexion-Extension Views' }] },
  { name: 'X-Ray: Upper Extremity', tests: [{ id: 'xray-shoulder', name: 'Shoulder X-ray' }, { id: 'xray-clavicle', name: 'Clavicle X-ray' }, { id: 'xray-ac-joint', name: 'AC Joint X-ray' }, { id: 'xray-humerus', name: 'Humerus X-ray' }, { id: 'xray-elbow', name: 'Elbow X-ray' }, { id: 'xray-forearm', name: 'Forearm X-ray' }, { id: 'xray-wrist', name: 'Wrist X-ray' }, { id: 'xray-hand', name: 'Hand X-ray' }, { id: 'xray-finger', name: 'Finger X-ray' }] },
  { name: 'X-Ray: Lower Extremity', tests: [{ id: 'xray-pelvis', name: 'Pelvis X-ray' }, { id: 'xray-hip', name: 'Hip X-ray' }, { id: 'xray-femur', name: 'Femur X-ray' }, { id: 'xray-knee', name: 'Knee X-ray' }, { id: 'xray-tibia-fibula', name: 'Tibia/Fibula X-ray' }, { id: 'xray-ankle', name: 'Ankle X-ray' }, { id: 'xray-foot', name: 'Foot X-ray' }, { id: 'xray-toe', name: 'Toe X-ray' }, { id: 'xray-calcaneus', name: 'Calcaneus X-ray' }, { id: 'xray-weight-bearing', name: 'Weight-Bearing Views' }] },
  { name: 'X-Ray: Head & Facial', tests: [{ id: 'xray-skull', name: 'Skull X-ray' }, { id: 'xray-facial-bones', name: 'Facial Bones X-ray' }, { id: 'xray-nasal-bones', name: 'Nasal Bones X-ray' }, { id: 'xray-mandible', name: 'Mandible X-ray' }, { id: 'xray-orbits', name: 'Orbits X-ray' }, { id: 'xray-tmj', name: 'TMJ X-ray' }, { id: 'xray-sinuses', name: 'Sinuses X-ray' }] },
  { name: 'X-Ray: Other', tests: [{ id: 'xray-soft-tissue-neck', name: 'Soft Tissue Neck X-ray' }, { id: 'xray-sternum', name: 'Sternum X-ray' }, { id: 'xray-bone-survey', name: 'Bone Survey' }, { id: 'xray-bone-age', name: 'Bone Age Study' }, { id: 'xray-skeletal-survey', name: 'Pediatric Skeletal Survey' }, { id: 'xray-babygram', name: 'Babygram' }] },
  { name: 'CT: Head & Neck', tests: [{ id: 'ct-head-non-contrast', name: 'CT Head (Non-Contrast)' }, { id: 'ct-head-contrast', name: 'CT Head (With Contrast)' }, { id: 'ct-head-with-without', name: 'CT Head (With & Without)' }, { id: 'ct-orbits', name: 'CT Orbits' }, { id: 'ct-sinuses', name: 'CT Sinuses' }, { id: 'ct-temporal-bones', name: 'CT Temporal Bones' }, { id: 'ct-neck-soft-tissue', name: 'CT Neck (Soft Tissue)' }, { id: 'ct-face', name: 'CT Face / Facial Bones' }, { id: 'ct-mandible', name: 'CT Mandible' }, { id: 'cta-head', name: 'CTA Head' }, { id: 'cta-neck', name: 'CTA Neck' }, { id: 'ct-perfusion-brain', name: 'CT Perfusion Brain' }] },
  { name: 'CT: Chest', tests: [{ id: 'ct-chest-non-contrast', name: 'CT Chest (Non-Contrast)' }, { id: 'ct-chest-contrast', name: 'CT Chest (With Contrast)' }, { id: 'ct-chest-with-without', name: 'CT Chest (With & Without)' }, { id: 'ctpa', name: 'CT Pulmonary Angiography (CTPA)' }, { id: 'ct-hrct', name: 'HRCT – ILD' }, { id: 'ct-chest-low-dose', name: 'CT Chest Low-Dose' }, { id: 'cta-thoracic-aorta', name: 'CTA Thoracic Aorta' }, { id: 'ct-calcium-score', name: 'CT Coronary Calcium Score' }, { id: 'ccta', name: 'CT Coronary Angiography (CCTA)' }] },
  { name: 'CT: Abdomen & Pelvis', tests: [{ id: 'ct-abdomen-non-contrast', name: 'CT Abdomen (Non-Contrast)' }, { id: 'ct-abdomen-contrast', name: 'CT Abdomen (With Contrast)' }, { id: 'ct-abdomen-pelvis-contrast', name: 'CT Abdomen & Pelvis' }, { id: 'ct-renal-stone', name: 'CT Renal Stone' }, { id: 'cta-abdominal-aorta', name: 'CTA Abdominal Aorta' }, { id: 'ct-liver-multiphase', name: 'CT Liver (Multiphase)' }, { id: 'ct-pancreas-multiphase', name: 'CT Pancreas' }, { id: 'ct-adrenal', name: 'CT Adrenal' }, { id: 'ct-kidney-multiphase', name: 'CT Kidney' }, { id: 'ct-pelvis', name: 'CT Pelvis' }] },
  { name: 'CT: Spine & MSK', tests: [{ id: 'ct-cervical-spine', name: 'CT Cervical Spine' }, { id: 'ct-thoracic-spine', name: 'CT Thoracic Spine' }, { id: 'ct-lumbar-spine', name: 'CT Lumbar Spine' }, { id: 'ct-shoulder', name: 'CT Shoulder' }, { id: 'ct-elbow', name: 'CT Elbow' }, { id: 'ct-wrist-hand', name: 'CT Wrist / Hand' }, { id: 'ct-hip', name: 'CT Hip' }, { id: 'ct-knee', name: 'CT Knee' }, { id: 'ct-ankle-foot', name: 'CT Ankle / Foot' }] },
  { name: 'MRI: Brain', tests: [{ id: 'mri-brain-non-contrast', name: 'MRI Brain (Without Contrast)' }, { id: 'mri-brain-with-without', name: 'MRI Brain (With & Without)' }, { id: 'mri-brain-dwi', name: 'MRI Brain with DWI' }, { id: 'mri-brain-epilepsy', name: 'MRI Brain – Epilepsy' }, { id: 'mri-pituitary', name: 'MRI Pituitary' }, { id: 'mri-brain-ms', name: 'MRI Brain – MS' }, { id: 'mri-brain-tumor', name: 'MRI Brain – Tumor' }, { id: 'mri-spectroscopy', name: 'MRI Spectroscopy' }, { id: 'fmri', name: 'fMRI' }] },
  { name: 'MRI: Head & Neck', tests: [{ id: 'mri-orbits', name: 'MRI Orbits' }, { id: 'mri-temporal-bones', name: 'MRI Temporal Bones' }, { id: 'mri-neck', name: 'MRI Neck' }, { id: 'mri-tmj', name: 'MRI TMJ' }, { id: 'mri-sinuses', name: 'MRI Sinuses' }, { id: 'mri-nasopharynx', name: 'MRI Nasopharynx' }, { id: 'mri-salivary-glands', name: 'MRI Salivary Glands' }, { id: 'mri-brachial-plexus', name: 'MRI Brachial Plexus' }] },
  { name: 'MRI: Spine', tests: [{ id: 'mri-cervical-non-contrast', name: 'MRI Cervical Spine' }, { id: 'mri-cervical-with-without', name: 'MRI Cervical Spine (With & Without)' }, { id: 'mri-thoracic-non-contrast', name: 'MRI Thoracic Spine' }, { id: 'mri-lumbar-non-contrast', name: 'MRI Lumbar Spine' }, { id: 'mri-lumbar-with-without', name: 'MRI Lumbar Spine (With & Without)' }, { id: 'mri-whole-spine', name: 'MRI Whole Spine' }, { id: 'mri-sacroiliac', name: 'MRI Sacroiliac Joints' }] },
  { name: 'MRI: Musculoskeletal', tests: [{ id: 'mri-shoulder', name: 'MRI Shoulder' }, { id: 'mri-elbow', name: 'MRI Elbow' }, { id: 'mri-wrist', name: 'MRI Wrist' }, { id: 'mri-hand', name: 'MRI Hand' }, { id: 'mri-hip', name: 'MRI Hip' }, { id: 'mri-knee', name: 'MRI Knee' }, { id: 'mri-ankle', name: 'MRI Ankle' }, { id: 'mri-foot', name: 'MRI Foot' }, { id: 'mri-arthrography', name: 'MRI Arthrography' }, { id: 'mri-whole-body', name: 'MRI Whole Body' }] },
  { name: 'MRI: Chest & Cardiac', tests: [{ id: 'mri-chest', name: 'MRI Chest' }, { id: 'cardiac-mri', name: 'Cardiac MRI' }, { id: 'cardiac-mri-stress', name: 'Cardiac MRI – Stress' }, { id: 'cardiac-mri-viability', name: 'Cardiac MRI – Viability' }, { id: 'mri-breast', name: 'MRI Breast' }, { id: 'mri-breast-screening', name: 'MRI Breast Screening' }] },
  { name: 'MRI: Abdomen & Pelvis', tests: [{ id: 'mri-abdomen-non-contrast', name: 'MRI Abdomen' }, { id: 'mri-abdomen-with-without', name: 'MRI Abdomen (With & Without)' }, { id: 'mri-liver-eovist', name: 'MRI Liver' }, { id: 'mrcp', name: 'MRCP' }, { id: 'mri-pancreas', name: 'MRI Pancreas' }, { id: 'mri-kidneys-adrenals', name: 'MRI Kidneys / Adrenals' }, { id: 'mri-pelvis-non-contrast', name: 'MRI Pelvis' }, { id: 'mri-prostate', name: 'MRI Prostate' }, { id: 'mri-rectum', name: 'MRI Rectum' }, { id: 'mri-female-pelvis', name: 'MRI Female Pelvis' }, { id: 'mri-fetal', name: 'MRI Fetal' }, { id: 'mri-enterography', name: 'MRI Enterography' }] },
  { name: 'MRI: Vascular', tests: [{ id: 'mra-brain', name: 'MRA Brain' }, { id: 'mra-neck', name: 'MRA Neck' }, { id: 'mra-thoracic-aorta', name: 'MRA Thoracic Aorta' }, { id: 'mra-abdominal-aorta', name: 'MRA Abdominal Aorta' }, { id: 'mra-renal', name: 'MRA Renal Arteries' }, { id: 'mra-lower-extremity', name: 'MRA Lower Extremity' }, { id: 'mr-venography', name: 'MR Venography' }] },
  { name: 'Ultrasound: Abdomen', tests: [{ id: 'us-abdomen-complete', name: 'Abdominal US (Complete)' }, { id: 'us-abdomen-limited', name: 'Abdominal US (Limited)' }, { id: 'us-ruq', name: 'RUQ US (Gallbladder)' }, { id: 'us-renal', name: 'Renal US' }, { id: 'us-liver-elastography', name: 'Liver US with Elastography' }, { id: 'us-hepatic-doppler', name: 'Hepatic Doppler US' }, { id: 'us-aortic', name: 'Aortic US' }, { id: 'us-appendix', name: 'Appendix US' }] },
  { name: 'Ultrasound: Pelvis', tests: [{ id: 'us-pelvic-transabdominal', name: 'Pelvic US (Transabdominal)' }, { id: 'us-transvaginal', name: 'Transvaginal US' }, { id: 'us-scrotal', name: 'Scrotal US' }, { id: 'us-penile-doppler', name: 'Penile Doppler US' }] },
  { name: 'Ultrasound: Obstetric', tests: [{ id: 'us-first-trimester', name: 'First Trimester US' }, { id: 'us-nt-scan', name: 'NT Scan' }, { id: 'us-anatomy-scan', name: 'Anatomy Scan (Level II)' }, { id: 'us-growth', name: 'Growth US' }, { id: 'us-bpp', name: 'BPP' }, { id: 'us-fetal-doppler', name: 'Fetal Doppler US' }, { id: 'us-cervical-length', name: 'Cervical Length' }, { id: 'us-dating-scan', name: 'Dating Scan' }] },
  { name: 'Ultrasound: Thyroid & Neck', tests: [{ id: 'us-thyroid', name: 'Thyroid US' }, { id: 'us-neck-lymph', name: 'Neck / Lymph Node US' }, { id: 'us-parathyroid', name: 'Parathyroid US' }, { id: 'us-salivary-gland', name: 'Salivary Gland US' }] },
  { name: 'Ultrasound: Breast', tests: [{ id: 'us-breast-bilateral', name: 'Breast US (Bilateral)' }, { id: 'us-breast-targeted', name: 'Breast US (Targeted)' }, { id: 'us-axillary', name: 'Axillary US' }] },
  { name: 'Ultrasound: Vascular', tests: [{ id: 'us-carotid-duplex', name: 'Carotid Duplex US' }, { id: 'us-lower-venous-dvt', name: 'Lower Extremity Venous (DVT)' }, { id: 'us-lower-arterial', name: 'Lower Extremity Arterial' }, { id: 'us-upper-arterial', name: 'Upper Extremity Arterial' }, { id: 'us-renal-artery-doppler', name: 'Renal Artery Doppler' }, { id: 'us-aorta-duplex', name: 'Abdominal Aorta Duplex' }, { id: 'us-tcd', name: 'Transcranial Doppler (TCD)' }] },
  { name: 'Ultrasound: Musculoskeletal', tests: [{ id: 'us-msk-shoulder', name: 'MSK US – Shoulder' }, { id: 'us-msk-elbow', name: 'MSK US – Elbow' }, { id: 'us-msk-wrist-hand', name: 'MSK US – Wrist / Hand' }, { id: 'us-msk-hip', name: 'MSK US – Hip' }, { id: 'us-msk-knee', name: 'MSK US – Knee' }, { id: 'us-msk-ankle-foot', name: 'MSK US – Ankle / Foot' }, { id: 'us-soft-tissue-mass', name: 'MSK US – Soft Tissue Mass' }] },
  { name: 'Nuclear Medicine', tests: [{ id: 'bone-scan', name: 'Bone Scan' }, { id: 'three-phase-bone-scan', name: 'Three-Phase Bone Scan' }, { id: 'mpi-stress-rest', name: 'Myocardial Perfusion Imaging' }, { id: 'muga-scan', name: 'MUGA Scan' }, { id: 'vq-scan', name: 'V/Q Scan' }, { id: 'thyroid-scan', name: 'Thyroid Scan' }, { id: 'thyroid-uptake', name: 'Thyroid Uptake Study' }, { id: 'renal-scan-mag3', name: 'Renal Scan (MAG3)' }, { id: 'hida-scan', name: 'HIDA Scan' }, { id: 'gastric-emptying', name: 'Gastric Emptying Study' }, { id: 'dat-scan', name: 'DaT Scan' }, { id: 'sentinel-node', name: 'Sentinel Lymph Node' }] },
  { name: 'PET/CT', tests: [{ id: 'fdg-pet-ct', name: 'FDG PET/CT (Oncology)' }, { id: 'psma-pet-ct', name: 'PSMA PET/CT (Prostate)' }, { id: 'dotatate-pet-ct', name: 'Dotatate PET/CT' }, { id: 'naf-pet-ct', name: 'NaF PET/CT' }, { id: 'fdg-pet-mri', name: 'FDG PET/MRI' }] },
  { name: 'Fluoroscopy', tests: [{ id: 'barium-swallow', name: 'Barium Swallow' }, { id: 'upper-gi-series', name: 'Upper GI Series' }, { id: 'sbft', name: 'Small Bowel Follow-Through' }, { id: 'barium-enema', name: 'Barium Enema' }, { id: 'ivp', name: 'IVP' }, { id: 'vcug', name: 'VCUG' }, { id: 'hsg', name: 'HSG' }, { id: 'myelography', name: 'Myelography' }] },
  { name: 'Mammography', tests: [{ id: 'screening-mammo', name: 'Screening Mammography' }, { id: 'diagnostic-mammo', name: 'Diagnostic Mammography' }, { id: 'tomosynthesis-3d', name: 'Tomosynthesis (3D)' }, { id: 'contrast-mammo', name: 'Contrast-Enhanced Mammography' }, { id: 'stereotactic-biopsy', name: 'Stereotactic Biopsy' }, { id: 'us-guided-breast-biopsy', name: 'US-Guided Breast Biopsy' }] },
  { name: 'Interventional Radiology', tests: [{ id: 'diagnostic-angiography', name: 'Diagnostic Angiography' }, { id: 'angioplasty', name: 'Angioplasty (PTA)' }, { id: 'stent-placement', name: 'Stent Placement' }, { id: 'embolization-hemorrhage', name: 'Embolization – Hemorrhage' }, { id: 'embolization-ufe', name: 'UFE' }, { id: 'ivc-filter', name: 'IVC Filter' }, { id: 'tips', name: 'TIPS' }, { id: 'ir-biopsy', name: 'Image-Guided Biopsy' }, { id: 'ir-abscess-drainage', name: 'Abscess Drainage' }, { id: 'rfa', name: 'RFA' }, { id: 'vertebroplasty', name: 'Vertebroplasty' }, { id: 'tace', name: 'TACE' }, { id: 'central-line', name: 'Central Line' }, { id: 'port-placement', name: 'Port Placement' }, { id: 'picc-line', name: 'PICC Line' }] },
  { name: 'DEXA', tests: [{ id: 'dexa-lumbar', name: 'DEXA – Lumbar Spine' }, { id: 'dexa-hip', name: 'DEXA – Hip' }, { id: 'dexa-forearm', name: 'DEXA – Forearm' }, { id: 'dexa-whole-body', name: 'DEXA – Whole Body' }] },
  { name: 'Dental', tests: [{ id: 'dental-panoramic', name: 'Dental Panoramic (OPG)' }, { id: 'dental-periapical', name: 'Dental Periapical' }, { id: 'dental-cbct', name: 'CBCT' }, { id: 'dental-cephalometric', name: 'Cephalometric' }] },
];

export const RADIOLOGY_LOOKUP: Record<string, { name: string; cat: string }> = {};
for (const cat of CATEGORIES) {
  for (const t of cat.tests) {
    RADIOLOGY_LOOKUP[t.id] = { name: t.name, cat: cat.name };
  }
}

export function groupRadiologyTests(testsObj: Record<string, boolean>): { cat: string; tests: string[] }[] {
  const groups: Record<string, string[]> = {};
  for (const [id, selected] of Object.entries(testsObj)) {
    if (!selected) continue;
    const found = RADIOLOGY_LOOKUP[id];
    const catName = found?.cat ?? 'Others';
    const testName = found?.name ?? id;
    if (!groups[catName]) groups[catName] = [];
    groups[catName].push(testName);
  }
  return Object.entries(groups).map(([cat, tests]) => ({ cat, tests }));
}
